### ISSUE TITLE
Need a loading screen

### ISSUE THREAD

**Issue by coolinker** [teem2/dreem2#38]
While user is waiting the app loads its js files and before app is initialized and shown, need to be able to show a loading spinner or progress bar for better user experience.

**Comment by maynarddemmon** [comment]
I've got some open source spinner code I've used in a bunch of places. I'll look into inserting that into the default html page returned by the server for a composition.

**Comment by maynarddemmon** [comment]
The dev branch now has a loading spinner div. If you want to modify it, look in core/compositionserver.js at line 301 for the function __getSpinnerCode. You can suppress the spinner with the query spinner=false.

**Comment by coolinker** [comment]
Cool!
